name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bundle exec jekyll build -d build
    - uses: actions/upload-artifact@master
      with:
        name: page
        path: build
        if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main